### ISSUE TITLE
Invalid update per PartiQL example

### ISSUE THREAD

**Issue by jo2** [awsdocs/aws-sdk-for-javascript-v3#98]
There seems to be an error in the documentation on how to [update an item in DynamoDB using PartiQL](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/javascript_dynamodb_code_examples.html).
The documentation gives the following example:
```
const params = {
  Statement:
    "UPDATE " + tableName + "  SET Producer=? where title=? and year=?",
  Parameters: [{ S: producer1 }, { S: movieTitle1 }, { N: movieYear1 }],
};
try {
  await ddbDocClient.send(new ExecuteStatementCommand(params));
  console.log("Success. Item updated.");
  return "Run successfully"; // For unit tests.
} catch (err) {
  console.error(err);
}
```
Using this for my code I get the following snippet:
```
const params = {
  Statement: `UPDATE Payment-${tableName} SET active=? WHERE subscriptionId=?`,
  Parameters: [{ BOOL: false }, { S: subscriptionId }],
};
return await docClient.send(new ExecuteStatementCommand(params));
```
`tableName` in this example is the suffix of my amplify-generated DynamoDB. I want to set the attribute active of all Items where subscriptionId equals a given string value to false.

As result I get this:
```
ValidationException: Statement wasn't well formed, can't be processed: Expected data manipulation
    at throwDefaultError (/var/runtime/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at deserializeAws_json1_0ExecuteStatementCommandError (/var/runtime/node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:1593:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async updatePayment (/var/task/index.js:54:12)
    at async exports.handler (/var/task/index.js:125:21) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'xxx',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'com.amazon.coral.validate#ValidationException'
}
```
Line 54 is the line where I call `docClient.send(..)`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
